name: Publish Docker
on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Build production image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/blueloveth/excalidraw:production
      - name: Get artifacts
        run: |
          container_id=$(docker run -itd ghcr.io/blueloveth/excalidraw:production)
          docker cp $container_id:/usr/share/nginx/html ./www
      - name: Publish to github page
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www
          token: ${{ secrets.PAT_ROOT }}